---
title: "Testing sg-converter function, Fenoprofen PK"
subtitle: "Volkova Alina"
author: "M&S Decisions, `r Sys.Date()`"
output: 
    bookdown::html_document2:
      toc: true
      toc_depth: 5
      toc_float:
        collapsed: true
        smooth_scroll: false
      number_sections: true
      code_folding: hide
      fig_width: 10
      fig_height: 7
      fig_caption: true
      
    officedown::rdocx_document:
      reference_docx: document_template.docx
---

```{r load-packages-and-set-global-settings, include=TRUE, warning = FALSE, message = FALSE}
rm(list=ls())
set.seed(123456)

library(tidyverse)
library(lubridate)
library(flextable)
library(officer)
library(officedown)
library(rxode2)
library(SimuRg)

theme_set(theme_bw())
theme_update(panel.grid.minor = element_blank())
MSDcol <- rep(c("#1a1866", "#f2b93b", "#b73b58", "#a2d630", "#5839bb", "#9c4ec7", "#3a6eba", "#efdd3c", "#69686d"), 10)
NEWcol <- c("dodgerblue", "seagreen2", "forestgreen", "orange2", "firebrick", "royalblue4",  "violetred1",  "black", "blue", "red", "purple", "gold", "skyblue3", "tan4", "plum2")

set_flextable_defaults(
  font.family = "Arial",
  font.size = 8,
  theme_fun = "theme_vanilla",
  table.layout = "autofit"
  )

knitr::opts_chunk$set(warning = FALSE, message = FALSE, echo = TRUE, fig.cap = TRUE, fig.align = "center", results = 'hide') 
if (!knitr::is_html_output()) {knitr::opts_chunk$set(include = FALSE)}
if (!knitr::is_html_output()) {
run_num_tab <- run_autonum(seq_id = "Table", pre_label = "Table ", bkm = "anytable")
run_num_fig <- run_autonum(seq_id = "Figure", pre_label = "Figure ", bkm = "anyfigure")
}
```

```{r load-functions}

```


```{r r-input}
#data_path <- "./workdir-av/projects/fenoprofen-pk/ds-fenoprofen-pk-mod.csv"
#model_path <- "./workdir-av/projects/fenoprofen-pk/model-pk-1c.txt"
project_name <- "1cmt-RE-Vd-CL-prop-FEMALE-on-Vd-CRCL-on-CL"
project_name_wo_cov <- "1cmt-RE-ka-Vd-CL-prop"
folder_path <- "./workdir-av/projects/fenoprofen-pk/Monolix/"

#data <- read_csv(data_path)

```

# sg-converter
```{r r-test-sg-converter}

# Convert Monolix project results with covariates
result <- sg_converter(folder_path = folder_path, proj_name = project_name)

save(result, file = str_c("./workdir-av/projects/fenoprofen-pk/", project_name, ".RData"))

# Convert Monolix project results without covariates
result_wo_cov <- sg_converter(folder_path = folder_path, proj_name = project_name_wo_cov)

save(result_wo_cov, file = str_c("./workdir-av/projects/fenoprofen-pk/", project_name_wo_cov, ".RData"))

# Access individual predictions
#head(result$SDTAB)

# View parameter estimates
#print(result$SUMTAB)

# Check objective function value
#print(result$OFV)


```

# sg-gof-obpr

```{r r-test-sg-gof-obpr}

# Basic plot
p0 <- sg_gof_obpr(fpath_i = str_c("./workdir-av/projects/fenoprofen-pk/", project_name, ".RData"))

# With categorical covariate and faceting
p1 <- sg_gof_obpr(
  fpath_i = str_c("./workdir-av/projects/fenoprofen-pk/", project_name, ".RData"),
  cov_cols = "FEMALE",
  col_i = "FEMALE",
  col_lab = "Female",
  facet_i = "FEMALE",
  addline = F,
  f_scales = "free",
  lab_y = "X-axis"
  #no_leg = T
  #abreaks = seq(0, 70, 5)
  #smooth = F,
  #log_axes = T
  #alpha_i = 0.1
)


# With several covariates and faceting
p3 <- sg_gof_obpr(
  fpath_i = str_c("./workdir-av/projects/fenoprofen-pk/", project_name, ".RData"),
  cov_cols = c("FEMALE", "SLE"),
  #col_i = "FEMALE",
  #col_lab = "Female",
  facet_i = "SLE",
  addline = F,
  f_scales = "free",
  #no_leg = T
  #abreaks = seq(0, 70, 5)
  #smooth = F,
  #log_axes = T
  #alpha_i = 0.1
)

# With continuous covariate and faceting
p4 <- sg_gof_obpr(
  fpath_i = str_c("./workdir-av/projects/fenoprofen-pk/", project_name, ".RData"),
  cov_cols = c("WTt"),
  #col_i = "FEMALE",
  #col_lab = "Female",
  facet_i = "WTt",
  addline = F,
  f_scales = "free",
  #no_leg = T
  #abreaks = seq(0, 70, 5)
  #smooth = F,
  #log_axes = T
  #alpha_i = 0.1
)

# With continuous covariate and faceting
p5 <- sg_gof_obpr(
  fpath_i = str_c("./workdir-av/projects/fenoprofen-pk/", project_name, ".RData"),
  cov_cols = c("WT"),
  col_i = "WT",
  col_lab = "Weight",
  facet_i = "WT",
  addline = F,
  f_scales = "free",
  n_quantiles = 4
  #no_leg = T
  #abreaks = seq(0, 70, 5)
  #smooth = F,
  #log_axes = T
  #alpha_i = 0.1
)


# population vs individual
#p <- sg_gof_obpr(
#  fpath_i = str_c("./workdir-av/projects/fenoprofen-pk/", project_name, ".RData"),
#  cov_cols = "FEMALE",
#  col_i = "FEMALE",
#  col_lab = "Female",
#  #facet_i = "FEMALE",
#  indiv = F
#)



```


# sg-gof-par-cov

```{r r-test-sg-gof-par-cov}

# RE
p0 <- sg_gof_par_cov(fpath_i = str_c("./workdir-av/projects/fenoprofen-pk/", project_name, ".RData"))

p0$re_vs_contcov
p0$re_vs_catcov

cat_cov <- tibble(
  COV = c("FEMALE", "SLE"),
  COVNAME = c("Sex, M/F", "SLE status")
)

p0 <- sg_gof_par_cov(fpath_i = str_c("./workdir-av/projects/fenoprofen-pk/", project_name, ".RData"),
                     cat_cov = cat_cov)

p0$re_vs_catcov

# IndPar
p1 <- sg_gof_par_cov(fpath_i = str_c("./workdir-av/projects/fenoprofen-pk/", project_name, ".RData"),
                     ptype = "IndParvsCov")

p1$ipar_vs_contcov
p1$ipar_vs_catcov


```

# sg_gof_par_dist

```{r r-test-sg-gof-par-dist}

# Basic plot
p0 <- sg_gof_par_dist(fpath_i = str_c("./workdir-av/projects/fenoprofen-pk/", project_name, ".RData"))

p0 <- sg_gof_par_dist(fpath_i = str_c("./workdir-av/projects/fenoprofen-pk/", project_name_wo_cov, ".RData"),
                      #n_bins = 10,
                      tdist = F)

# Plot with prespecified parameters
p1 <- sg_gof_par_dist(fpath_i = str_c("./workdir-av/projects/fenoprofen-pk/", project_name, ".RData"), eta_seq = c("CL", "Vd"))

# QQ plot
p2 <- sg_gof_par_dist(fpath_i = str_c("./workdir-av/projects/fenoprofen-pk/", project_name, ".RData"), eta_seq = c("CL", "Vd"), plot_type = "QQ")

p2 <- sg_gof_par_dist(fpath_i = str_c("./workdir-av/projects/fenoprofen-pk/", project_name_wo_cov, ".RData"), plot_type = "QQ")

# correlations
p3 <- sg_gof_par_dist(fpath_i = str_c("./workdir-av/projects/fenoprofen-pk/", project_name, ".RData"), eta_seq = c("CL", "Vd"), plot_type = "correlations")

p3 <- sg_gof_par_dist(fpath_i = str_c("./workdir-av/projects/fenoprofen-pk/", project_name_wo_cov, ".RData"), plot_type = "correlations")


```



### Section 3

```{r plot-chunk-name-1, fig.id = "plot-chunk-name-1", fig.width = 10, fig.height = 3.75, fig.cap = "Figure caption"}
# ggplot()
```

```{r table-chunk-name-1, results = 'asis', tab.cap = "Table caption"}
# flextable(tab_out) %>% set_table_properties(width = 1, layout = "autofit") %>% hline(part = "body")
```

# R Runtime Environment {.tabset}
## Current R session {.unnumbered}
```{r sourcefile}
source_file <- basename(rstudioapi::getSourceEditorContext()$path)
```

**Source file:** `r source_file`
```{r rsession, results='asis'}
# Print a record of the environment in which this script was rendered
info <- sessionInfo()
```

```{r tab-rsession-env}
# R Version
info$R.version %>%
  as.data.frame() %>%
  select(version.string, platform) %>%
  rename(
    `R version` = version.string,
    Platform = platform
  ) %>%
  flextable() %>%
  set_table_properties(width = 1, layout = "autofit")
```

## Base Packages {.unnumbered}
```{r tab-rsession-base}
# Base Packages
tibble(Package = info$basePkgs) %>%
  arrange(Package) %>%
  flextable() %>% 
  set_table_properties(layout = "autofit", width = 0.4)
```

## Attached Packages {.unnumbered}
```{r tab-rsession-attached}
# Attached Packages
info$otherPkgs %>%
  purrr::map_dfr(~ tibble(Package = .x$Package, Version = .x$Version)) %>%
  arrange(Package) %>%
  flextable() %>%
  set_table_properties(layout = "autofit", width = 0.4)
```

## Loaded Packages {.unnumbered}
```{r tab-rsession-loaded}
# Loaded Packages
info$loadedOnly %>%
  purrr::map_dfr(~ tibble(Package = .x$Package, Version = .x$Version)) %>%
  arrange(Package) %>%
  flextable() %>%
  set_table_properties(layout = "autofit", width = 0.4)
```

## {-}