## Author: Ugolkov Yaroslav
## First created: 2025-09-05
## Description: sg-gof-par-dist and its helper functions
## Keywords: SimuRg, sg-gof-par-dist, goodness-of-fit
#'
#' Plot distributions of individual parameters with optional theoretical density
#'@description
#' This function creates histograms of individual parameter estimates,
#' with optional overlay of the theoretical distribution based on the population parameters and OMEGA matrix.
#'
#' @inheritParams sg_dummy
#'
#' @param plot_type Character string specifying the type of plot to generate.
#'   Options: 'DIST' for parameter distributions (default), 'QQ' for Q-Q plots,
#'   'correlations' for correlation matrix plot.
#' @return A `ggplot` object containing histogram(s) of individual parameter distributions, optionally overlaid with theoretical densities.
#'
#' @details
#' The function visualizes the distribution of post hoc individual parameter estimates (from `$PATAB`) and compares them with the expected population-level variability assuming log-normal distribution.
#' Shrinkage values are calculated based on `ETAshrinkage_sd` from `$SUMTAB` and included in facet labels.
#'
#' Theoretical distributions are generated by sampling from a multivariate normal distribution (mean zero, covariance from `$OMEGAMAT`) and transforming to the log-normal scale using the typical values (`VALUE` column of `$SUMTAB`).
#'
#'
#' @examples
#' # Basic usage
#' fpath_i <- system.file("extdata", "simurg_object", "Warfarin_PK.RData", package = "SimuRg")
#' sg_gof_par_dist(fpath_i = fpath_i)
#'
#' # Only for specific parameters
#' sg_gof_par_dist(fpath_i = fpath_i, eta_seq = c("ka", "Cl"))
#' @import dplyr, y
#' @importFrom MASS mvrnorm
#' @import ggplot2
#' @importFrom scales pretty_breaks
#' @export
devtools::load_all()

sg_gof_par_dist <- function(fpath_i, eta_seq = NULL, n_bins = 30, tdist = T, plot_type = 'DIST'){
  if (inherits(fpath_i, "character")) {smrg_obj <- get(load(fpath_i))}  else if (inherits(fpath_i, "list")) {    smrg_obj <- fpath_i  } else {    	stop("fpath_i object should be either an sg_fit object, or a path to saved sg_fit object")  }

  prm_i <- smrg_obj$COVMAT
  patab_i <- smrg_obj$PATAB
  omegamat_i <- smrg_obj$OMEGAMAT
  ### Distribution of individual parameters
  if(is.null(eta_seq)){
    eta_seq <- names(patab_i %>% select(-contains("eta"),-ID))
    eta_seq <- eta_seq[eta_seq %in% sub("^omega_", "", colnames(omegamat_i))]
  }


  # if (plot_type == 'correlations') {
  #   if(is.null(eta_seq)){
  #     selected_cols <- setdiff(names(patab_i), "ID")
  #   } else {
  #     selected_cols <- eta_seq
  #   }
  #
  #   ds_eta <- patab_i %>% select(ID, all_of(selected_cols))
  #
  #   lowerFn <- function(data, mapping, method = "lm") {
  #     ggplot(data = data, mapping = mapping) +
  #       geom_point(alpha = 0.8) +
  #       geom_smooth(formula = "y ~ x", method = method, color = MSDcol[3], se = FALSE, linewidth = 1) +
  #       geom_smooth(formula = "y ~ x", method = "loess", color = MSDcol[2], se = FALSE, linewidth = 1)
  #   }
  #
  #   diagFn <- function(data, mapping) {
  #     ggplot(data = data, mapping = mapping) +
  #       geom_histogram(aes(y = after_stat(density)), alpha = 0.6, col = "grey45",
  #                      fill = MSDcol[2], bins = 10) +
  #       geom_density(alpha = 0.3, col = "black", fill = MSDcol[2]) +
  #       geom_vline(xintercept = 0, col = "grey25", linetype = "dotted", linewidth = 0.5)
  #   }
  #
  #   upperFn <- function(data, mapping) {
  #     GGally::ggally_cor(data = data, mapping = mapping,
  #                        size = 4, color = "black")
  #   }
  #
  #   p_i <- GGally::ggpairs(
  #     select(ds_eta, -ID,-eta_Vd,    -eta_CL),
  #     lower = list(continuous = GGally::wrap(lowerFn)),
  #     diag = list(continuous = GGally::wrap(diagFn)),
  #     upper = list(continuous = GGally::wrap(upperFn))
  #   )
  #
  #   return(p_i)
  # }
  if (plot_type == 'correlations') {
    # Prepare data
    if(is.null(eta_seq)){
      selected_cols <- setdiff(names(patab_i), "ID")
    } else {
      selected_cols <- eta_seq
    }

    ds_eta <- patab_i %>% dplyr::select(ID, dplyr::all_of(selected_cols))
    plot_cols <- setdiff(names(ds_eta), c("ID", "eta_Vd", "eta_CL"))
    n <- length(plot_cols)

    # Save current graphics parameters
    old_par <- par(no.readonly = TRUE)

    # Create layout for plots
    par(mfrow = c(n, n),
        mar = c(1.5, 1.5, 0.5, 0.5),
        oma = c(2, 2, 2, 1))

    for(i in 1:n) {
      for(j in 1:n) {
        if(i == j) {
          # DIAGONAL - histogram with density
          # First draw empty plot with histogram stats to set proper ylim
          h <- hist(ds_eta[[plot_cols[i]]], plot = FALSE, breaks = 10)

          plot(1, type = "n",
               xlim = range(ds_eta[[plot_cols[i]]]),
               ylim = c(0, max(h$density) * 1.1),
               xlab = "", ylab = "",
               axes = TRUE, cex.axis = 1, mgp = c(2, 0.5, 0))

          # Add grid
          grid(col = "grey80", lty = 1, lwd = 0.5)

          # Add histogram
          hist(ds_eta[[plot_cols[i]]],
               main = "",
               xlab = "",
               ylab = "",
               col = MSDcol[2],
               border = "grey45",
               probability = TRUE,
               breaks = 10,
               add = TRUE)

          box()

          # Density curve
          lines(density(ds_eta[[plot_cols[i]]]),
                col = "grey25",
                lwd = 1.7)

          # Vertical line at 0
          abline(v = 0, col = "grey25", lty = 3, lwd = 1)

        } else if(i < j) {
          # UPPER TRIANGLE - Pearson correlation with significance stars
          plot(1, type = "n",
               xlim = c(0, 1), ylim = c(0, 1),
               xlab = "", ylab = "",
               xaxt = "n", yaxt = "n",
               axes = FALSE)
          box()

          # Pearson correlation
          cor_test <- cor.test(ds_eta[[plot_cols[i]]], ds_eta[[plot_cols[j]]],
                               method = "pearson", use = "complete.obs")
          cor_val <- cor_test$estimate
          p_val <- cor_test$p.value

          # Significance stars
          stars <- ifelse(p_val < 0.001, "***",
                          ifelse(p_val < 0.01, "**",
                                 ifelse(p_val < 0.05, "*", "")))

          # Correlation text with stars
          text(0.5, 0.6,
               labels = paste0("Pearson correlation = ", round(cor_val, 2), stars),
               cex = 1.3,
               font = 2,
               col = "black")

        } else {
          # LOWER TRIANGLE - scatter plot with regression line
          plot(ds_eta[[plot_cols[j]]], ds_eta[[plot_cols[i]]],
               pch = 16,
               col = MSDcol[1],
               xlab = "",
               ylab = "",
               cex = 1,
               axes = TRUE,
               cex.axis = 1,
               mgp = c(2, 0.5, 0))

          # Add grid
          grid(col = "grey80", lty = 1, lwd = 0.5)

          # Redraw points on top of grid
          points(ds_eta[[plot_cols[j]]], ds_eta[[plot_cols[i]]],
                 pch = 16, col = MSDcol[1], cex = 1)

          box()

          # Linear regression line
          abline(lm(ds_eta[[plot_cols[i]]] ~ ds_eta[[plot_cols[j]]]),
                 col = MSDcol[3],
                 lwd = 1.5)
        }
      }
    }

    # Add variable labels on TOP
    for(j in 1:n) {
      mtext(plot_cols[j],
            side = 3, line = 0.2, outer = TRUE,
            at = (j - 0.5)/n, cex = 1, font = 2)
    }

    # Add variable labels on LEFT
    for(i in 1:n) {
      mtext(plot_cols[i],
            side = 2, line = 0.2, outer = TRUE,
            at = (n - i + 0.5)/n, cex = 1, font = 2)
    }

    # Capture the plot
    p_i <- recordPlot()

    # Restore graphics parameters
    par(old_par)

    return(p_i)
  }



  ### Calculate shrinkage
  shr_out <- smrg_obj$SUMTAB %>% filter(grepl("^omega_", PAR)) %>% select(ETAshrinkage_sd,VALUE,PAR) %>% mutate(PAR = str_remove(PAR, "^omega_"), Shrinkage = signif(ETAshrinkage_sd,3) )



  ind_par_dist <- patab_i %>% select(all_of(eta_seq)) %>%
    gather("PAR") %>%
    left_join(shr_out, by = "PAR") %>%
    mutate(
      Shrinkage = ifelse(is.na(Shrinkage), "N/A", Shrinkage),
      LABEL = str_c(PAR, "\nShrinkage = ", Shrinkage, "%"))


    p_i <- ggplot(data = ind_par_dist, aes(x = value)) +
      geom_histogram(aes(y = after_stat(density)),
                     bins = n_bins,
                     col = "grey25",
                     fill = MSDcol[2]) +
      theme_bw()+
      facet_wrap(~PAR, scales = "free") +
    scale_y_continuous(name = "Density", breaks = scales::pretty_breaks(7), expand = c(0, 0), limits = c(0, NA)) +
    scale_x_continuous(name = "Parameter value", breaks = scales::pretty_breaks(7), expand = c(0, 0))

  suppressMessages({
    # tdist считается только для plot_type = 'DIST'
    if(tdist && plot_type == 'DIST'){

      par_pop <- smrg_obj$SUMTAB %>%
        filter(str_detect(PAR, "_pop$")) %>%
        mutate(PAR = str_remove(PAR, "_pop$")) %>%
        select(PAR, TV = VALUE) %>%
        filter(PAR %in% eta_seq)  # Фильтруем только нужные параметры

      colnames(omegamat_i) <- sub("^omega_", "", colnames(omegamat_i))
      rownames(omegamat_i) <- sub("^omega_", "", rownames(omegamat_i))
      rownames(omegamat_i) <- colnames(omegamat_i)
      omega_subset <- omegamat_i[par_pop$PAR, par_pop$PAR, drop = FALSE]


      n_eta <- ncol(omega_subset)

      gen_eta <- MASS::mvrnorm(
        n = 1000,
        mu = rep(0, n_eta),
        Sigma = omega_subset
      ) %>%
        as_tibble() %>%
        setNames(par_pop$PAR) %>%
        pivot_longer(cols = everything(), names_to = "PAR", values_to = "ETA") %>%
        left_join(par_pop, by = "PAR") %>%
        mutate(TDIST = TV * exp(ETA)) %>%
        left_join(ind_par_dist %>% select(PAR, LABEL) %>% distinct(), by = "PAR")

      p_i <- p_i + geom_density(
        data = gen_eta,
        aes(x = TDIST),
        linewidth = 0.8,
        lty = "dashed") +
        facet_wrap(~LABEL, scales = "free")

    }
    if (plot_type == 'QQ') {
      eta_df <- patab_i %>%
        select(ID, starts_with("eta_")) %>%
        pivot_longer(cols = starts_with("eta_"), names_to = "PAR", values_to = "ETA") %>%
        mutate(PAR = sub("^eta_", "", PAR))

      p_i <- ggplot(eta_df, aes(sample = ETA)) +
        stat_qq(size = 1.75, color = MSDcol[1], alpha = 0.8) +
        stat_qq_line(col = MSDcol[3]) +
        labs(x = "Theoretical quantiles", y = "Sample quantiles") +
        geom_abline(linewidth = 0.5, col = "black", linetype = "dashed") +
        scale_x_continuous(breaks = scales::pretty_breaks(7)) +
        scale_y_continuous(breaks = scales::pretty_breaks(7)) +
        theme_bw()+
        facet_wrap(~PAR, scales = "free")
    }
  })
  return(p_i)
}


### Alinas code ####
project_name <- "1cmt-RE-Vd-CL-prop-FEMALE-on-Vd-CRCL-on-CL"
project_name_wo_cov <- "1cmt-RE-ka-Vd-CL-prop"

# Basic plot
sg_gof_par_dist(fpath_i = str_c("./scripts/nlme/3.5-sg-gof-par-dist/", project_name, ".RData"),
                tdist =  F)

sg_gof_par_dist(fpath_i = str_c("./scripts/nlme/3.5-sg-gof-par-dist/", project_name_wo_cov, ".RData"),
                      #n_bins = 10,
                      tdist =  T)

# Plot with prespecified parameters
sg_gof_par_dist(fpath_i = str_c("./scripts/nlme/3.5-sg-gof-par-dist/", project_name, ".RData"), eta_seq = c("CL", "Vd"))

# QQ plot
sg_gof_par_dist(fpath_i = str_c("./scripts/nlme/3.5-sg-gof-par-dist/", project_name, ".RData"), eta_seq = c("CL", "Vd"), plot_type = "QQ")

sg_gof_par_dist(fpath_i = str_c("./scripts/nlme/3.5-sg-gof-par-dist/", project_name_wo_cov, ".RData"), plot_type = "QQ")

# correlations
sg_gof_par_dist(fpath_i = str_c("./scripts/nlme/3.5-sg-gof-par-dist/", project_name, ".RData"), eta_seq = c("CL", "Vd"), plot_type = "correlations")

 sg_gof_par_dist(fpath_i = str_c("./scripts/nlme/3.5-sg-gof-par-dist/", project_name_wo_cov, ".RData"), plot_type = "correlations")

