## Author: Ugolkov Yaroslav
## First created: 2025-09-05
## Description: sg-gof-par-dist and its helper functions
## Keywords: SimuRg, sg-gof-par-dist, goodness-of-fit
#'
#' Plot Distributions of Individual Parameters with Optional Theoretical Density
#'@description
#' This function creates histograms of individual parameter estimates,
#' with optional overlay of the theoretical distribution based on the population parameters and OMEGA matrix.
#'
#' @inheritParams sg_dummy
#'
#' @return A `ggplot` object containing histogram(s) of individual parameter distributions, optionally overlaid with theoretical densities.
#'
#' @details
#' The function visualizes the distribution of post hoc individual parameter estimates (from `$PATAB`) and compares them with the expected population-level variability assuming log-normal distribution.
#' Shrinkage values are calculated based on `ETAshrinkage_sd` from `$SUMTAB` and included in facet labels.
#'
#' Theoretical distributions are generated by sampling from a multivariate normal distribution (mean zero, covariance from `$OMEGAMAT`) and transforming to the log-normal scale using the typical values (`VALUE` column of `$SUMTAB`).
#'
#'
#' @examples
#' \dontrun{
#' # Basic usage
#' sg_gof_par_dist(fpath_i = "PK.RData")
#'
#' # Only for specific parameters
#' sg_gof_par_dist(fpath_i = "~/Simurg_function/Warfarin_PK.RData", eta_seq = c("ka", "Cl"))
#' }
#' @import dplyr
#' @import ggplot2
#' @importFrom scales pretty_breaks
#' @export

sg_gof_par_dist <- function(fpath_i, eta_seq = NULL, n_bins = 30, tdist = T,plot_type = 'DIST'){
  smrg_obj <- read_smrg_obj(fpath_i)
  if (is.null(smrg_obj$PATAB) | is.null(smrg_obj$SUMTAB)) {
    stop("sg_fit object must contain COVMAT, PATAB and SUMTAB components")
  }
  patab_i <- smrg_obj$PATAB
  sumtab_i <- smrg_obj$SUMTAB

  if (is.data.frame(patab_i) && nrow(patab_i) == 0) {
    stop("PATAB is empty (no rows)")
  } else if (is.data.frame(sumtab_i) && nrow(sumtab_i) == 0) stop("SUMTAB is empty (no rows)")

  if (is.list(patab_i) && length(patab_i) == 0) {
    stop("PATAB is empty (no elements)")
  } else if (is.list(sumtab_i) && length(sumtab_i) == 0)  stop("SUMTAB is empty (no elements)")

  if (is.data.frame(patab_i)) { patab_i <- patab_i
  } else if (is.list(patab_i)) { patab_i <- as.data.frame(do.call(rbind, patab_i))
  } else stop("PATAB must be a data frame or a list of data frames")

  if (is.data.frame(sumtab_i)) { sumtab_i <- sumtab_i
  } else if (is.list(sumtab_i)) {sumtab_i <- as.data.frame(do.call(rbind, sumtab_i))
  } else stop("SUMTAB must be a data frame or a list of data frames")



  ### Calculate shrinkage
  shr_out <- sumtab_i %>% filter(grepl("_pop$", PAR)) %>% select(ETAshrinkage_sd,VALUE,PAR) %>% mutate(PAR = str_remove(PAR, "_pop$"), Shrinkage = signif(ETAshrinkage_sd,3) )

  ### Distribution of individual parameters
  if(is.null(eta_seq)){
    eta_seq <- names(patab_i %>% select(-contains("eta"),-ID))
  }
  # eta_seq_r<- patab_i %>% select(-contains("eta"),-ID)
  ind_par_dist <- patab_i %>% select(eta_seq) %>% gather("PAR") %>% left_join(shr_out, by = "PAR") %>% mutate(LABEL = str_c(PAR, "\nShrinkage = ", Shrinkage, "%"))

  p_i <- ggplot(data = ind_par_dist, aes(x = value, y = ..density..)) +
    geom_histogram(bins = n_bins, col = "grey25", fill = MSDcol[2]) +
    facet_wrap(~LABEL, scales = "free") +
    theme_bw() +
    theme(panel.grid.minor = element_blank()) +
    scale_y_continuous(name = "Density", breaks = scales::pretty_breaks(7), expand = c(0, 0), lim = c(0, NA)) +
    scale_x_continuous(name = "Parameter value", breaks = scales::pretty_breaks(7), expand = c(0, 0))
  suppressMessages({
    if(tdist){

      par_pop <- smrg_obj$SUMTAB %>%
        filter(str_detect(PAR, "_pop$")) %>%
        mutate(PAR = str_remove(PAR, "_pop$")) %>%
        select(PAR, TV = VALUE)

      gen_par_set <- MASS::mvrnorm(100000, rep(0, nrow(par_pop)), smrg_obj$OMEGAMAT) %>%
        as_tibble() %>%
        setNames(par_pop$PAR) %>%
        pivot_longer(cols = everything(), names_to = "PAR", values_to = "ETA") %>%
        left_join(par_pop, by = "PAR") %>%
        mutate(TDIST = TV * exp(ETA)) %>%
        left_join(ind_par_dist %>% select(PAR,LABEL),relationship = "many-to-many") %>% filter(PAR %in% eta_seq)
      unique(gen_par_set$PAR)
      p_i <- p_i + geom_density(data = gen_par_set, aes(x = TDIST), size = 0.8, lty = "dashed")

    }
    if (plot_type == 'QQ') {
      p_i <- ggplot(ind_par_dist, aes(sample = value)) +
      stat_qq(size = 1.75, color = MSDcol[1], alpha = 0.8) +
      stat_qq_line(col = "firebrick") +
      labs(x = "Theoretical quantiles", y = "Sample quantiles") +
      geom_abline(size = 0.5, col = "black", linetype = "dashed") +
      scale_x_continuous(breaks = scales::pretty_breaks(7)) +
      scale_y_continuous(breaks = scales::pretty_breaks(7)) +
      theme_bw() +
      theme(panel.grid.minor = element_blank()) +
      facet_wrap(~PAR, scales = "free")
    }
  })
  return(p_i)

}


